### ISSUE TITLE
.version file for KSP-AVC points to incorrect URL

### ISSUE THREAD

**Issue by ghost** [raidernick/BDAnimationModules#1]
Currently pointing to:
http://raw.githubusercontent.com/raidernick/BDAnimationModules/master/GameData/BahaSP/BDAnimationModules.version

Should be:
https://raw.githubusercontent.com/raidernick/BDAnimationModules/master/BahaSP/BDAnimationModules.version

Hence currently kspavc does not notify about new releases...

**Comment by raidernick** [comment]
fixed
