### ISSUE TITLE
AnimatedThrust doesn't disable all the other engine gimbles

### ISSUE THREAD

**Issue by linuxgurugamer** [raidernick/BDAnimationModules#2]
I'm working on reviving some of Baha's old parts which use this.

This cfg code:
`	MODULE
	{
		name = AnimatedThrust
		ThrustAnimationName = vjthrust2
		disableGimbalToggle = true
	}
`
isn't working, when I right-click the engine, I see 25-30 gimble lines.

**Comment by linuxgurugamer** [comment]
Fixe din the PR I just made

**Comment by raidernick** [comment]
fixed and released
