### ISSUE TITLE
Log spam due to disabled gimbals after recent fix

### ISSUE THREAD

**Issue by ghost** [raidernick/BDAnimationModules#4]
The most recent fix results in log spam "Disabling gimbal actions" on engines which have their gimbal options disabled in config.

Suggest to remove the "Debug.Log(...)" line related to this in AnimatedThrust.cs, line 127.

**Comment by raidernick** [comment]
should be fixed here: https://github.com/raidernick/BDAnimationModules/releases/tag/v0.6.5.1
