### ISSUE TITLE
Error in .version file

### ISSUE THREAD

**Issue by linuxgurugamer** [raidernick/BDAnimationModules#5]
The .version file supplied with the BDAnimation mod has a syntax error, there is a comma following the word "false" at line 9.  This causes JSON errors with MiniAVC and AVC

I would have submitted a PR, but I couldn't find the .version file in the repo

**Comment by raidernick** [comment]
fixed https://github.com/raidernick/BDAnimationModules/releases/tag/v0.6.5.4
